### ISSUE TITLE
Zretezene casti nazvu

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/adresar-knihoven-api#1]
Napr. pro:
https://cpk-back.mzk.cz:8443/siglainf/getinfo?sigla=aba001
je v library.name.cs:
"Národní knihovna České republikyKnihovní fondy a službyOdbor služeb"
Predpokladam, ze v MARCu je tento nazev strukturovany na 3 casti a pri zpracovani dojde k zretezeni vsech casti do jednoho stringu.

Bud pridat mezi casti pomlcku obalenou mezerama, nebo lepe, vracet strukturovany nazev i JSONu.

**Comment by matussabik** [comment]
V JSONu sa už posiela štrukturovaný názov vytiahnutý z MARCu.

Ďalšia komplikácia vzniká pri anglickom názve, lebo element s id VAR sa nachádza v MARCu dvakrát.

``` xml
<varfield id="VAR" i1="1" i2=" ">
<subfield label="a">Národní knihovna ČR</subfield>
<subfield label="b">Knihovní fondy a služby</subfield>
<subfield label="c">Odbor služeb</subfield>
</varfield>
<varfield id="VAR" i1="2" i2=" ">
<subfield label="a">National Library of the Czech Republic</subfield>
<subfield label="b">Library Collection and Services</subfield>
<subfield label="c">Public Services Division</subfield>
</varfield>
```

Dá sa predpokladať že anglický názov má vždy atribút i1="2" ?

**Comment by honza-rychtar** [comment]
Takto je popsan anglicky nazev ve funkcni analyze pro knihovny.cz:

metadata.record.datafield
{tag="VAR" AND ind1="2"}
.subfield{code=”a”}

Takze ano, brat jen i1="2"
Ale nepredpokladat, ze tam je :)
Pokud tam id="VAR" && i1="2" neni, pak asi anglicky nazev vubec neuvadet, tj. nebrat ten z id="VAR" && i1="1"

**Comment by matussabik** [comment]
Hotovo. Aj server v NK už beží.
