### ISSUE TITLE
Lepší chybová hláška při výpadku aleph.nkp.cz

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/adresar-knihoven-api#2]
Momentálně vůbec nejede aleph.nkp.cz. Adresář knihoven vyhazuje tuto hlášku:

![](http://i.imgur.com/MWe22EN.png)

Snad se jedná o ojedinělou záležitost, jinak by bylo vhodné ta data posbírat dopředu :-(

**Comment by leiblix** [comment]
Z FB stránek NK

 `Z důvodu přerušení dodávky elektrické energie budou v neděli 21. června v době 7-15 hod. mimo provoz veškeré aplikace NK včetně webových stránek. Galerie Klementinum bude 21. 6. uzavřena. Omlouváme se a děkujeme za pochopení.`

**Comment by honza-rychtar** [comment]
Data by bylo lepsi posbirat tak ci tak.
Ja je mam sklizene, takze na Alephu zavisly nejsem - http://czech-libraries.herokuapp.com/libraries/sigla/boa001

Kdyz MKP bude resit web knihovny.cz pres jineho dodavatele. 
Tak pokud budete chtit tak vam tu sluzbu - http://czech-libraries.herokuapp.com/ - dam.

**Comment by matussabik** [comment]
Služba teraz pri výpadku spojenia vracia:
{"error": "Service is temporarily unavailable."}

**Comment by honza-rychtar** [comment]
Jeste by bylo dobre nevracet status 200.
Nejlepe vratit 422.
Pokud nastane tato situace, tak pri pouziti sluzby nema smysl parsovat odpoved a hledat error, ale jen kouknout na status code a pokud neni 200, tak telo odpovedi neresit.

**Comment by matussabik** [comment]
Už sa vracia status 422. V tele odpovedi sa nachádzajú podrobnosti, tie samozrejme netreba nijako spracovávať.
